import { SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import ActivityCard from "../../../components/ui/ActivityCard";
import EmptyState from "../../../components/ui/EmptyState";
import { activities, categories } from "../../../data/mockData";
function ExplorePage(){
 const [params]=useSearchParams(); const [text,setText]=useState(""); const [city,setCity]=useState(params.get("city")||""); const [category,setCategory]=useState(params.get("category")||""); const [budget,setBudget]=useState(""); const [favorites,setFavorites]=useState(()=>JSON.parse(localStorage.getItem("cityspot_favorites")||"[]"));
 const result=useMemo(()=>activities.filter(a=>a.status==="ACTIVA"&&(!text||a.name.toLowerCase().includes(text.toLowerCase()))&&(!city||a.city.toLowerCase().includes(city.toLowerCase()))&&(!category||a.category===category)&&(!budget||a.referencePrice<=Number(budget))),[text,city,category,budget]);
 const toggle=a=>{const next=favorites.includes(a.id)?favorites.filter(id=>id!==a.id):[...favorites,a.id];setFavorites(next);localStorage.setItem("cityspot_favorites",JSON.stringify(next));};
 return <main className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><div><p className="font-semibold text-brand-700">Explorar</p><h1 className="text-3xl font-black text-slate-950">Encuentra actividades</h1><p className="mt-2 text-slate-500">Filtra por ciudad, categoría y presupuesto.</p></div><div className="mt-8 grid gap-6 lg:grid-cols-[280px_1fr]"><aside className="h-fit rounded-2xl border bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-bold"><SlidersHorizontal size={18}/>Filtros</h2><div className="mt-5 space-y-4"><label className="block text-sm font-medium">Buscar<input value={text} onChange={e=>setText(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2.5 outline-none focus:border-brand-600" placeholder="Nombre de actividad"/></label><label className="block text-sm font-medium">Ciudad<input value={city} onChange={e=>setCity(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2.5 outline-none focus:border-brand-600" placeholder="Quito, Cuenca..."/></label><label className="block text-sm font-medium">Categoría<select value={category} onChange={e=>setCategory(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2.5"><option value="">Todas</option>{categories.map(c=><option key={c.id}>{c.name}</option>)}</select></label><label className="block text-sm font-medium">Presupuesto máximo<input type="number" min="0" value={budget} onChange={e=>setBudget(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2.5" placeholder="$0"/></label><button onClick={()=>{setText("");setCity("");setCategory("");setBudget("")}} className="w-full rounded-xl border px-4 py-2.5 text-sm font-semibold">Limpiar filtros</button></div></aside><section><div className="mb-5 flex items-center justify-between"><p className="text-sm text-slate-500"><strong className="text-slate-900">{result.length}</strong> resultados</p></div>{result.length?<div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{result.map(a=><ActivityCard key={a.id} activity={a} favorite={favorites.includes(a.id)} onFavorite={toggle}/>)}</div>:<EmptyState/>}</section></div></main>
}
export default ExplorePage;
