import { ArrowRight, MapPin, Search, Sparkles } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { useState } from "react";
import ActivityCard from "../../../components/ui/ActivityCard";
import { activities, categories } from "../../../data/mockData";
function HomePage(){
 const navigate=useNavigate(); const [city,setCity]=useState(""); const [category,setCategory]=useState("");
 const submit=e=>{e.preventDefault(); navigate(`/activities?city=${encodeURIComponent(city)}&category=${encodeURIComponent(category)}`)};
 return <main><section className="relative overflow-hidden bg-gradient-to-br from-brand-900 via-brand-700 to-cyan-600 text-white"><div className="absolute inset-0 opacity-20 [background-image:radial-gradient(circle_at_20%_20%,white_0,transparent_28%),radial-gradient(circle_at_80%_60%,white_0,transparent_24%)]"/><div className="relative mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:py-28"><div className="max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full bg-white/15 px-4 py-2 text-sm font-medium"><Sparkles size={16}/>Explora Ecuador de una forma diferente</span><h1 className="mt-6 text-4xl font-black leading-tight sm:text-6xl">Encuentra tu próxima experiencia inolvidable</h1><p className="mt-5 max-w-2xl text-lg text-teal-50">Actividades, cultura, gastronomía y naturaleza reunidas en un solo lugar.</p></div><form onSubmit={submit} className="mt-10 grid max-w-4xl gap-3 rounded-2xl bg-white p-3 shadow-2xl md:grid-cols-[1fr_1fr_auto]"><label className="flex items-center gap-3 rounded-xl bg-slate-50 px-4"><MapPin className="text-brand-600" size={20}/><input value={city} onChange={e=>setCity(e.target.value)} placeholder="¿En qué ciudad?" className="w-full bg-transparent py-4 text-slate-900 outline-none"/></label><label className="flex items-center gap-3 rounded-xl bg-slate-50 px-4"><Search className="text-brand-600" size={20}/><select value={category} onChange={e=>setCategory(e.target.value)} className="w-full bg-transparent py-4 text-slate-900 outline-none"><option value="">Todas las categorías</option>{categories.map(c=><option key={c.id}>{c.name}</option>)}</select></label><button className="rounded-xl bg-brand-600 px-7 py-4 font-bold text-white hover:bg-brand-700">Buscar</button></form></div></section>
 <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6"><div className="flex items-end justify-between"><div><p className="font-semibold text-brand-700">Categorías</p><h2 className="mt-1 text-3xl font-black text-slate-950">Elige cómo quieres explorar</h2></div><Link to="/activities" className="hidden items-center gap-2 font-semibold text-brand-700 sm:flex">Ver todas <ArrowRight size={18}/></Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.map((c,i)=><Link key={c.id} to={`/activities?category=${c.name}`} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm hover:border-brand-300 hover:shadow-md"><div className="grid h-12 w-12 place-items-center rounded-xl bg-brand-50 text-xl font-black text-brand-700">{i+1}</div><h3 className="mt-5 text-lg font-bold">{c.name}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{c.description}</p></Link>)}</div></section>
 <section className="bg-white py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6"><p className="font-semibold text-brand-700">Recomendaciones</p><h2 className="mt-1 text-3xl font-black">Experiencias destacadas</h2><div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{activities.filter(a=>a.status==="ACTIVA").slice(0,3).map(a=><ActivityCard key={a.id} activity={a}/>)}</div></div></section></main>
}
export default HomePage;
